version: "3"

services:
  db:
    image: mongo:latest
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  api:
    build: .
    image: api
    container_name: api
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo_user:mongo_password@db:27017
      - MONGO_DB=api
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
  db_config:
